//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public Calls()
        {
            this.Jobs = new HashSet<Jobs>();
        }
    
        public int CallID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CustomerName { get; set; }
        public string CallNumber { get; set; }
        public string CustomerMail { get; set; }
        public string CallDesc { get; set; }
        public bool CallStatus { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Jobs> Jobs { get; set; }
    }
}
