//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public int JobID { get; set; }
        public Nullable<int> CallID { get; set; }
        public string Cari { get; set; }
        public string CariAdres { get; set; }
        public string Gruplar { get; set; }
        public string Teknisyenler { get; set; }
        public bool Acil { get; set; }
        public bool Kapali { get; set; }
        public string KTarih { get; set; }
        public string Musteri { get; set; }
    
        public virtual Calls Calls { get; set; }
    }
}
