//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StajProjeEntities : DbContext
    {
        public StajProjeEntities()
            : base("name=StajProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Calls> Calls { get; set; }
        public DbSet<Jobs> Jobs { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
